{{- range .Values.secrets }}
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  fields:
    {{- range .fields }}
    - fieldName: {{ .fieldName }}
      length: {{ .length | default "32" | quote }}
      {{- with .encoding }}
      encoding: {{ . }}
      {{- end }}
    {{- end }}
{{- end }}
